name: metworkpy
channels:
  - conda-forge
dependencies:
  - python=3.13
  - cobra
  - highspy
  - matplotlib
  - jupyter
  - matplotlib
  - networkx
  - osqp
  - openpyxl
  - pip
  - scipy
  - pip:
    - iplotx
    - hopsy
    - ..
